import type { FastifyBaseLogger } from 'fastify';
import { config } from '../config/env.js';
import * as giteaApi from '../integrations/gitea/giteaApi.js';
import type { GitHubReview, GitHubReviewComment } from '../integrations/github/githubApi.js';
import { withRetry } from '../utils/retry.js';

export interface ReviewPublishInput {
  giteaRepo: string;
  giteaPrNumber: number;
  githubRepo: string;
  githubPrNumber: number;
  review: GitHubReview;
  comments: GitHubReviewComment[];
}

function formatMvpComment(input: ReviewPublishInput): string {
  const { githubRepo, githubPrNumber, review, comments } = input;
  const lines: string[] = [];

  lines.push(`## 🤖 Copilot Code Review (GitHub)`);
  lines.push('');
  lines.push(`**GitHub PR:** ${githubRepo}#${githubPrNumber}`);
  lines.push(`**Review ID:** ${review.id}`);

  if (review.body) {
    lines.push('');
    lines.push(`### Resumen`);
    lines.push('');
    lines.push(review.body);
  }

  if (comments.length > 0) {
    lines.push('');
    lines.push(`### Comentarios inline`);
    lines.push('');
    for (const c of comments) {
      const line = c.line ?? c.original_line ?? '?';
      lines.push(`- \`${c.path}:${line}\` — ${c.body}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push(`_Generated by ReviewRelay — ${new Date().toISOString()}_`);

  return lines.join('\n');
}

function mapGitHubSideToGiteaPosition(
  comment: GitHubReviewComment,
): Pick<giteaApi.GiteaReviewComment, 'old_position' | 'new_position'> {
  const lineNum = comment.line ?? comment.original_line ?? 0;
  if (lineNum === 0) return {};
  if (comment.side === 'LEFT') {
    return { old_position: lineNum };
  }
  // Default to RIGHT / new_position
  return { new_position: lineNum };
}

async function publishAsReview(input: ReviewPublishInput, log: FastifyBaseLogger): Promise<void> {
  const giteaComments: giteaApi.GiteaReviewComment[] = input.comments.map((c) => ({
    path: c.path,
    body: c.body,
    ...mapGitHubSideToGiteaPosition(c),
  }));

  const event =
    input.review.state === 'APPROVED'
      ? 'APPROVED'
      : input.review.state === 'CHANGES_REQUESTED'
        ? 'REQUEST_CHANGES'
        : 'COMMENT';

  try {
    await withRetry(() =>
      giteaApi.createPullReview(input.giteaRepo, input.giteaPrNumber, {
        body: input.review.body || `Copilot Code Review (GitHub ${input.githubRepo}#${input.githubPrNumber})`,
        event: event as 'COMMENT' | 'APPROVED' | 'REQUEST_CHANGES',
        comments: giteaComments,
      }),
    );
    log.info(
      { giteaRepo: input.giteaRepo, prNumber: input.giteaPrNumber },
      'Published V2 review to Gitea',
    );
  } catch (err) {
    log.warn(
      { err },
      'V2 review publish failed, falling back to MVP comment',
    );
    await publishAsComment(input);
  }
}

async function publishAsComment(input: ReviewPublishInput): Promise<void> {
  const markdown = formatMvpComment(input);
  await withRetry(() =>
    giteaApi.createIssueComment(input.giteaRepo, input.giteaPrNumber, markdown),
  );
}

export async function publishReview(
  input: ReviewPublishInput,
  log: FastifyBaseLogger,
): Promise<void> {
  if (config.PUBLISH_MODE === 'review') {
    await publishAsReview(input, log);
  } else {
    await publishAsComment(input);
  }
}

// Exported for testing
export { formatMvpComment, mapGitHubSideToGiteaPosition };
