import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../../config/env.js', () => ({
  config: {
    PUBLISH_MODE: 'comment',
  },
}));

vi.mock('../../integrations/gitea/giteaApi.js', () => ({
  createIssueComment: vi.fn().mockResolvedValue(undefined),
  createPullReview: vi.fn().mockResolvedValue(undefined),
}));

vi.mock('../../utils/retry.js', () => ({
  withRetry: (fn: () => unknown) => fn(),
}));

import { formatMvpComment, mapGitHubSideToGiteaPosition } from '../reviewPublishService.js';
import type { ReviewPublishInput } from '../reviewPublishService.js';
import type { GitHubReviewComment } from '../../integrations/github/githubApi.js';

function makeInput(overrides?: Partial<ReviewPublishInput>): ReviewPublishInput {
  return {
    giteaRepo: 'org/repo',
    giteaPrNumber: 1,
    githubRepo: 'org/mirror',
    githubPrNumber: 10,
    review: {
      id: 100,
      body: 'Looks good overall',
      state: 'COMMENTED',
      user: { login: 'github-copilot[bot]' },
    },
    comments: [],
    ...overrides,
  };
}

describe('formatMvpComment', () => {
  it('formats a comment with review body and no inline comments', () => {
    const md = formatMvpComment(makeInput());
    expect(md).toContain('## 🤖 Copilot Code Review (GitHub)');
    expect(md).toContain('**GitHub PR:** org/mirror#10');
    expect(md).toContain('**Review ID:** 100');
    expect(md).toContain('### Resumen');
    expect(md).toContain('Looks good overall');
    expect(md).not.toContain('### Comentarios inline');
    expect(md).toContain('Generated by ReviewRelay');
  });

  it('formats a comment without review body', () => {
    const md = formatMvpComment(
      makeInput({ review: { id: 100, body: null, state: 'COMMENTED', user: null } }),
    );
    expect(md).not.toContain('### Resumen');
  });

  it('includes inline comments when present', () => {
    const comments: GitHubReviewComment[] = [
      {
        id: 1,
        path: 'src/app.ts',
        line: 42,
        side: 'RIGHT',
        body: 'Fix this',
        original_line: null,
      },
      {
        id: 2,
        path: 'src/utils.ts',
        line: null,
        side: 'LEFT',
        body: 'Old issue',
        original_line: 10,
      },
    ];
    const md = formatMvpComment(makeInput({ comments }));
    expect(md).toContain('### Comentarios inline');
    expect(md).toContain('`src/app.ts:42`');
    expect(md).toContain('`src/utils.ts:10`');
  });
});

describe('mapGitHubSideToGiteaPosition', () => {
  it('maps RIGHT side to new_position', () => {
    const result = mapGitHubSideToGiteaPosition({
      id: 1,
      path: 'a.ts',
      line: 5,
      side: 'RIGHT',
      body: 'x',
      original_line: null,
    });
    expect(result).toEqual({ new_position: 5 });
  });

  it('maps LEFT side to old_position', () => {
    const result = mapGitHubSideToGiteaPosition({
      id: 1,
      path: 'a.ts',
      line: 3,
      side: 'LEFT',
      body: 'x',
      original_line: null,
    });
    expect(result).toEqual({ old_position: 3 });
  });

  it('falls back to original_line when line is null', () => {
    const result = mapGitHubSideToGiteaPosition({
      id: 1,
      path: 'a.ts',
      line: null,
      side: 'RIGHT',
      body: 'x',
      original_line: 7,
    });
    expect(result).toEqual({ new_position: 7 });
  });

  it('returns empty when both line and original_line are null', () => {
    const result = mapGitHubSideToGiteaPosition({
      id: 1,
      path: 'a.ts',
      line: null,
      side: 'RIGHT',
      body: 'x',
      original_line: null,
    });
    expect(result).toEqual({});
  });
});
